// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4b8g1MPja-SLwGoWr-pgIpKjirSmPq50',
    appId: '1:49702341614:web:88006e493223d318b15cff',
    messagingSenderId: '49702341614',
    projectId: 'pokedex-9604c',
    authDomain: 'pokedex-9604c.firebaseapp.com',
    storageBucket: 'pokedex-9604c.firebasestorage.app',
    measurementId: 'G-Z9KQYPC4P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr_gxNXxnP-dN8hlJWRVsJLG7BYsR9y88',
    appId: '1:49702341614:android:3cd5cf63c0a6a26cb15cff',
    messagingSenderId: '49702341614',
    projectId: 'pokedex-9604c',
    storageBucket: 'pokedex-9604c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAci2Dgj8ZoKyogeWHHJjESR1c_bxzD1X0',
    appId: '1:49702341614:ios:135e83b64524a0c2b15cff',
    messagingSenderId: '49702341614',
    projectId: 'pokedex-9604c',
    storageBucket: 'pokedex-9604c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAci2Dgj8ZoKyogeWHHJjESR1c_bxzD1X0',
    appId: '1:49702341614:ios:135e83b64524a0c2b15cff',
    messagingSenderId: '49702341614',
    projectId: 'pokedex-9604c',
    storageBucket: 'pokedex-9604c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4b8g1MPja-SLwGoWr-pgIpKjirSmPq50',
    appId: '1:49702341614:web:47247d4c64f1b298b15cff',
    messagingSenderId: '49702341614',
    projectId: 'pokedex-9604c',
    authDomain: 'pokedex-9604c.firebaseapp.com',
    storageBucket: 'pokedex-9604c.firebasestorage.app',
    measurementId: 'G-HXC63LPXJH',
  );
}
